class PlaceTypes {
  static Map<String, String> types = {
    'accounting': 'Kế toán',
    'airport': 'Sân bay',
    'amusement_park': 'Công viên giải trí',
    'aquarium': 'Bể nuôi cá',
    'art_gallery': 'Triển lãm nghệ thuật',
    'atm': 'ATM',
    'bakery': 'Cửa hàng bánh mì',
    'bank': 'Ngân hàng',
    'bar': 'Quán ba',
    'beauty_salon': 'Thẩm mỹ viện',
    'bicycle_store': 'Xe đạp_cửa hàng',
    'book_store': 'Cửa hàng sách',
    'bowling_alley': 'Sân chơi bowling',
    'bus_station': 'Trạm xe buýt',
    'cafe': 'Quán cà phê',
    'campground': 'Nơi cắm trại',
    'car_dealer': 'Người bán ô tô',
    'car_rental': 'Thuê ô tô',
    'car_repair': 'Sửa chữa ô tô',
    'car_wash': 'Rửa xe',
    'casino': 'Sòng bạc',
    'cemetery': 'Nghĩa trang',
    'church': 'Nhà thờ',
    'city_hall': 'Toà thị chính',
    'clothing_store': 'Cửa hàng quần áo',
    'convenience_store': 'Cửa hàng tiện dụng',
    'courthouse': 'Tòa án',
    'dentist': 'Nha sĩ',
    'department_store': 'Cửa hàng bách hóa',
    'doctor': 'Bác sĩ',
    'drugstore': 'Nhà thuốc',
    'electrician': 'Thợ điện',
    'electronics_store': 'Cửa hàng điện tử',
    'embassy': 'Đại sứ quán',
    'fire_station': 'Trạm cứu hỏa',
    'florist': 'Người bán hoa',
    'funeral_home': 'Nhà tang lễ',
    'furniture_store': 'Cửa hàng nội thất',
    'gas_station': 'Trạm xăng',
    'gym': 'Phòng thể dục',
    'hair_care': 'Chăm sóc tóc',
    'hardware_store': 'Cửa hàng phần cứng',
    'hindu_temple': 'Đền hindu',
    'home_goods_store': 'Nhà_hàng_cửa hàng',
    'hospital': 'Bệnh viện',
    'insurance_agency': 'Cơ quan bảo hiểm',
    'jewelry_store': 'Cửa hàng nữ trang',
    'laundry': 'Giặt ủi',
    'lawyer': 'Luật sư',
    'library': 'Thư viện',
    'light_rail_station': 'Ga đường sắt nhẹ',
    'liquor_store': 'Cửa hàng rượu',
    'local_government_office': 'Văn phòng chính quyền địa phương',
    'locksmith': 'Thợ khóa',
    'lodging': 'Chỗ ở',
    'meal_delivery': 'Bữa ăn_giao hàng',
    'meal_takeaway': 'Bữa_mua',
    'mosque': 'Nhà thờ hồi giáo',
    'movie_rental': 'Thuê phim',
    'movie_theater': 'Rạp chiếu phim',
    'moving_company': 'Công ty di chuyển',
    'museum': 'Bảo tàng',
    'night_club': 'Câu lạc bộ đêm',
    'painter': 'Họa sĩ',
    'park': 'Công viên',
    'parking': 'Bãi đậu xe',
    'pet_store': 'Của hàng vật nuôi',
    'pharmacy': 'Tiệm thuốc',
    'physiotherapist': 'Nhà vật lý trị liệu',
    'plumber': 'Thợ sửa ống nước',
    'police': 'Cảnh sát',
    'post_office': 'Bưu điện',
    'primary_school': 'Trường tiểu học',
    'real_estate_agency': 'Cơ quan bất động sản',
    'restaurant': 'Nhà hàng',
    'roofing_contractor': 'Lợp_nhà thầu',
    'rv_park': 'Rv_park',
    'school': 'Trường học',
    'secondary_school': 'Trường cấp hai',
    'shoe_store': 'Cửa hàng giày',
    'shopping_mall': 'Trung tâm mua sắm',
    'spa': 'Spa',
    'stadium': 'Sân vận động',
    'storage': 'Kho',
    'store': 'Cửa hàng',
    'subway_station': 'Ga tàu điện ngầm',
    'supermarket': 'Siêu thị',
    'synagogue': 'Hội đường',
    'taxi_stand': 'Đón taxi',
    'tourist_attraction': 'Du_lich',
    'train_station': 'Ga xe lửa',
    'transit_station': 'Quá cảnh_trạm',
    'travel_agency': 'Đại lý du lịch',
    'university': 'Trường đại học',
    'veterinary_care': 'Chăm sóc thú y',
    'zoo': 'Vườn bách thú',
  };
}
